services:
  frontend-dev:
    image: node:22-alpine
    container_name: clinica-farma-frontend-dev
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - clinica-network

networks:
  clinica-network:
    driver: bridge

volumes:
  node_modules: