version: '3.8'

services:
  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinica-farma-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - clinica-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "com.clinica.description=Frontend React SI CLINICA FARMA"
      - "com.clinica.version=1.0.0"

  # Backend (placeholder para cuando lo tengas)
  # backend:
  #   image: clinica-backend:latest
  #   container_name: clinica-backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - NODE_ENV=production
  #     - DB_HOST=database
  #   depends_on:
  #     - database
  #   restart: unless-stopped
  #   networks:
  #     - clinica-network

  # Base de datos PostgreSQL
  # database:
  #   image: postgres:15-alpine
  #   container_name: clinica-db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_DB=clinica_farma
  #     - POSTGRES_USER=clinica_user
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - clinica-network

networks:
  clinica-network:
    driver: bridge

# volumes:
#   postgres_data: